dcrajasthan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from packages.sitemap import *

sitemaps = {
    'static': StaticViewSitemap,
    'category': CategorySitemap,
    'tour': TourSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('testimonials/', include('testimonials.urls', namespace='testimonials')),
    path('packages/', include('packages.urls', namespace='packages')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import *

app_name = 'pages'

urlpatterns = [
    path('', home, name='home'),
    path('tours', tours, name='tours'),
    path('about_us', aboutUs, name="about"),
    path('contact_us', contactUs, name="contact"),
    path('query', send_query, name="query"),
    path('faq', faq, name="faq"),
    path('gallery', gallery, name="gallery"),
    path('team_profile', team_profile, name="team_profile"),
    path('terms_and_conditions', terms_and_conditions, name="terms_and_conditions")
]

testimonials/urls.py
from django.urls import re_path
from .views import createTestimonial

app_name = 'testimonials'

urlpatterns = [
    re_path(r'create/$', createTestimonial, name='create'),
]

testimonials/models.py
from django.db import models


class Testimonials(models.Model):
    name = models.CharField(max_length=30)
    review = models.TextField()
    image = models.ImageField(upload_to='testimonials')
    approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Clients'
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.name

testimonials/forms.py
from django import forms
from .models import Testimonials


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonials
        fields = ('name', 'review', 'image')

testimonials/views.py
from django.template.loader import render_to_string
from django.conf import settings
from django.shortcuts import render, redirect
from pages.tasks import sendMail
from .forms import TestimonialForm
from .models import *
from .selectors import getTestimonial


def createTestimonial(request):
    if request.method == 'POST':
        form = TestimonialForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            testimonial = getTestimonial(form.cleaned_data['name'])
            template_approval = render_to_string('testimonials_approve.html', {
                'name' : form.cleaned_data['name'],
                'link' : f'{request.build_absolute_uri("/")[:-1]}/admin/testimonials/testimonials/{testimonial.id}/change/'
            })

            sendMail.delay(settings.EMAIL_HOST_USER, template_approval, 'New Review Received')
            return redirect('pages:home')
    else:
        form = TestimonialForm()
    return render(request, 'testimonial_form.html', {
        'form': form
    })

templates/all_tours.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

	Epic Rajasthan Tours | All Tours | Filtered Tours

{% endblock %}

{% block content %}

	{{block.super}}

	<!-- SubHeader =============================================== -->
	<section class="parallax_window_in" data-parallax="scroll" data-image-src="{% static 'img/tours_banner.jpg' %}" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro">
				<h1>Tours</h1>
				<p>"Find your appropriate Tour with us"</p>
			</div>
		</div>
	</section>
	<!-- End section -->
	<!-- End SubHeader ============================================ -->


	<section class="wrapper">
		<div class="divider_border_gray"></div>

		<form action="{% url 'packages:filter_tours' %}" method="GET">
			<div class="row" style="margin-right: 0; margin-left: 0;">
				<div class="col-md-2 col">
					<div id="filters" class="clearfix">
						<select name="price" class="form-control">
							<option value=""> Select Price </option>
							<option value="5000,10000">5000 - 10000</option>
							<option value="11000,30000">11000 - 30000</option>
							<option value="31000,50000">31000 - 50000</option>
							<option value="51000,2147483647">51000 - Unlimited</option>
						</select>
					</div>
				</div>
				<div class="col-md-2 col">
					<div id="filters" class="clearfix">
						<input type="text" class="form-control" placeholder="Location" name="location">
					</div>
				</div>
				<div class="col-md-2 col">
					<div id="filters" class="clearfix">
						<select name="theme" class="form-control">
							<option value=""> Select Theme </option>
							{% for category in categories %}
							<option value="{{category.title}}">{{category.title}}</option>
							{% endfor %}

						</select>
					</div>
				</div>
				<div class="col-md-2 col">
					<div id="filters" class="clearfix">
						<input type="submit" class="btn btn-primary" value="search">
					</div>
				</div>
			</div>
		</form>

		<div class="container">
			<div class="row">
				{% if tours_count == 0 %}

					<div class="alert alert-danger">No Tours Available Yet!</div>
				
				{% else %}

					{% for tour in tours %}

					<div class="col-md-4 col-sm-6 wow fadeIn animated" data-wow-delay="0.2s">
						<div class="img_wrapper">
							<div class="ribbon">
								<span>Popular</span>
							</div>
							{% if tour.price_is_active == True %}
							<div class="price_grid">
								<sup><i class="icon-rupee"></i></sup>
								{{tour.price}}
							</div>
							{% endif %}
							<div class="img_container">
								<a href="{% url 'packages:tour' tour.category.slug tour.slug %}">
									<img src="{{ tour.image.url }}" style="width: 800px; height: 240px;" class="img-responsive" alt="{{tour.title}}">
									<div class="short_info">
										<h3>{{tour.title}}</h3>
										<em>{{tour.tourdetail.num_of_days}} Days & {{tour.tourdetail.num_of_nights}} Nights</em>
										<p>
											{{tour.description|truncatewords:10}}
										</p>
									</div>
								</a>
							</div>
						</div>
						<!-- End img_wrapper -->
					</div>
					<!-- End col -->
					{% endfor %}
				{% endif %}
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</section>
	<!-- End section -->


	<div class="container margin_60"></div>


{% endblock %}


{% block footer %}

	{{ block.super }}

{% endblock %}


{% block specificscripts %}

	<!-- SPECIFIC SCRIPTS -->
	<script src="{% static 'js/jquery.selectbox-0.2.js' %}"></script>
	<script>
		$(".selectbox").selectbox();
	</script>

{% endblock %}

templates/category.html
<div class="row">
   {% for package in packages %}
      {% if package.is_active == True %}
         <div class="col-md-4 col-sm-6 wow fadeIn animated" data-wow-delay="0.2s">
            <div class="img_wrapper">
               <div class="img_container">
                  <a href="{% url 'packages:category' slug=package.slug %}">
                     <img src="{{ package.image.url }}" style="width: 100%; height: 250px;" alt="{{ package.title }}">
                     <div class="short_info">
                        <h3>{{ package.title }}</h3>
                        <p>{{ package.description|truncatewords:15 }}</p>
                     </div>
                  </a>
               </div>
            </div>
         </div>
      {% endif %}
   {% endfor %}
</div>
<!-- End row -->

templates/choose_us.html
<div class="row">
   <div class="col-sm-4">
      <div class="box_how">
         <div class="icon_how"><span class="icon_set_1_icon-81"></span>
         </div>
         <h4><b>BEST PRICE GUARANTEE</b></h4>
         <p>
            Feed Your Wanderlust Economically
         </p>
      </div>
   </div>
   <div class="col-sm-4">
      <div class="box_how">
         <div class="icon_how"><span class="icon_set_1_icon-94"></span>
         </div>
         <h4><b>PROFESSIONAL LOCAL GUIDES</b></h4>
         <p>
            Explore Your Tour With Our Profound Guides
         </p>
      </div>
   </div>
   <div class="col-sm-4">
      <div class="box_how">
         <div class="icon_how"><span class="icon_set_1_icon-92"></span>
         </div>
         <h4><b>CERTIFICATE OF EXCELLENCE</b></h4>
         <p>
            Years Of Excellence With Proficient Employees
         </p>
      </div>
   </div>
</div>
<!-- End Row -->

templates/contact_inquiry.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Epic Rajasthan Tours | contact Inquriy</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      #MessageViewBody a {
        color: inherit;
        text-decoration: none;
        font-size: inherit;
        font-family: inherit;
        font-weight: inherit;
        line-height: inherit;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Hello {{first_name}} {{last_name}} </p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Thanks for visiting  <a href="https://epicrajasthanttours.com">epicrajasthanttours.com</a> and giving us a chance to serve you. Your query request has been acknowledged and our travel consultants are working on it to provide you with the best deal. We will get back to you shortly. If you need any information urgently, please contact us at the address/contact number provided.<br></p>        
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"><b>About Us</b><br></p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"><a href="https://epicrajasthanttours.com">epicrajasthanttours.com</a> is a start-up travel organization in the Indian tourism industry with experts who have an experience of more than two decades. A professional company backed with an expert team proficient in catering to various market segments and in understanding the nuances of tourism in India. <br> <br>
                        For any urgent requirement please contact:<br> 
                        <a href="tel://009891549078">+91-9891549078</a>
                        <br>
                        <a href="tel://008851548286">+91-8851548286</a>
                        </p><br>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Contact Info:<br>
                          Epic Rajasthan Tours and Travels. <br>
                          SRS 101 National Market,<br>
                          Peeragarhi, New Delhi-110087<br><br>

                          Website: <a href="https://epicrajasthanttours.com">epicrajasthanttours.com</a> <br>

                          E-mail: <a href="mailto:business@epicrajasthanttours.com">business@epicrajasthanttours.com</a>
                        </p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>


          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>

templates/footer.html
<footer>
   <div class="container">
      <div class="row">
         <div class="col-md-3 col-sm-3">
            <h3>Need help?</h3>
            <a href="tel://008851548286" id="phone">+91 8851548286</a>
            <a href="mailto:business@epicrajasthantours.com" id="email_footer">business@epicrajasthantours.com</a>
         </div>
         <div class="col-md-2 col-sm-3">
            <h3>About</h3>
            <ul>
               <li><a href="{% url 'pages:about' %}">About us</a>
               </li>
               <li><a href="{% url 'pages:faq' %}">FAQ</a>
               </li>
               <li><a href="{% url 'pages:terms_and_conditions' %}">Terms and condition</a>
               </li>
            </ul>
         </div>
      </div>
      <!-- End row -->
      <hr>
      <div class="row">
         <div class="col-sm-8">
            <span id="copy">© EpicRajasthanTours 2020 - All rights reserved</span>
         </div>
         <div class="col-sm-4" id="social_footer">
            <ul>
               <li><a href="https://www.facebook.com/discoverrajasthanwithdharmender/"><i class="icon-facebook"></i></a>
               </li>
               <li><a href="https://www.instagram.com/discoverrajasthanwithdarmender/?hl=en"><i class="icon-instagram"></i></a>
               </li>
               <li><a href="https://api.whatsapp.com/send?phone=918851548286&text=Hello Anshu Shokeen! I want to know about tours and guides."><i class="icon-chat"></i></a>
               </li>
            </ul>
         </div>
      </div>
      <!-- End row -->
   </div>
   <!-- End container -->
</footer>
<!-- End footer -->

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Epic Rajasthan Tours | Home
{% endblock %}

{% block specificcss %}
	<link href="{% static 'css/layerslider.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

	<style>
		.layer-is-visible {
			visibility: hidden;
		}
	</style>

	<div class="layer"></div>

	{{ block.super }}

	<!-- Slider -->
	{% include 'slider.html' %}
	<!-- End Slider -->

	<section class="wrapper">
		<div class="divider_border"></div>
		<div class="container">

			<div class="main_title">
				<h2>Our <span>Top</span> packages</h2>
				<p>Choose the package of your interest</p>
			</div>
			
			{% include 'category.html' %}

		</div>
	</section>
	<!-- End section -->

	<section class="container margin_60">
		<div class="main_title">
			<h3>Why choose us</h3>
			<p>
				Don't listen to us, Experience it!
			</p>
		</div>
		
		{% include 'choose_us.html' %}

	</section>
	<!-- End Container -->

	<section class="promo_full">
		<div class="promo_full_wp">
			<div>
				<h3>What Our Clients Says<span>Bring Fun In Your Trip With Us</span></h3>
				
				{% include 'testimonials.html' %}

			</div>
			<!-- End promo_full_wp -->
		</div>
		<!-- End promo_full -->
	</section>
	<!-- End section -->
	
{% endblock %}

{% block footer %}

	{{ block.super }}

{% endblock %}


{% block specificscripts %}
	<!-- SPECIFIC SCRIPTS -->
	<script src="{% static 'js/greensock.js' %}"></script>
	<script src="{% static 'js/layerslider.transitions.js' %}"></script>
	<script src="{% static 'js/layerslider.kreaturamedia.jquery.js' %}"></script>
	<script>
		'use strict';
		$('#layerslider').layerSlider({
			autoStart: true,
			navButtons: false,
			navStartStop: false,
			showCircleTimer: false,
			responsive: true,
			responsiveUnder: 1080,
			layersContainer: 1200,
			skinsPath: '/static/css/'
		});
	</script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block title %}

	DISCOVER RAJASTHAN | ALL TOURS

{% endblock %}

{% block content %}

	{{block.super}}

	<!-- SubHeader =============================================== -->
	<section class="parallax_window_in" data-parallax="scroll" data-image-src="img/sub_header_list_museum.jpg" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro">
				<h1>Available Tours</h1>
				<p>search results for "{{ q }}"</p>
			</div>
		</div>
	</section>
	<!-- End section -->
	<!-- End SubHeader ============================================ -->


	<section class="wrapper">
		<div class="divider_border_gray"></div>
		<div class="container">

			{% if tours %}
				{% for tour in tours %}
				<div class="row strip_list wow fadeIn animated" data-wow-delay="0.2s">
					<div class="col-md-5">
						<div class="img_wrapper">
							<div class="ribbon">
								<span>Popular</span>
							</div>
							<div class="price_grid">
								<sup><i class="icon-rupee"></i></sup>{{ tour.tourdetail.price }}
							</div>
							<div class="img_container">
								<a href="{% url 'packages:tour' tour.category.slug tour.slug %}">
									<img src="{{ tour.image.url }}" width="800" height="533" class="img-responsive" alt="">
									<div class="short_info">
										<em>{{ tour.title }}</em>
									</div>
								</a>
							</div>
						</div>
						<!-- End img_wrapper -->
					</div>
					<div class="col-md-7">
						<h3>{{ tour.title }}</h3>
						<p>{{ tour.tourdetail.description }}</p>
						<p><a href="{% url 'packages:tour' tour.category.slug tour.slug %}" class="btn_1">Read more</a>
						</p>
					</div>
				</div>
				<!-- End strip list -->
				{% endfor %}
				<!-- End row -->
			{% else %}
				<div class="alert alert-danger">No Tours Available Yet!</div>
			{% endif %}
		</div>
		<!-- End container -->
		</section>
	<!-- End section -->


	<div class="container margin_60"></div>


{% endblock %}


{% block footer %}

	{{ block.super }}

{% endblock %}


{% block specificscripts %}

	<!-- SPECIFIC SCRIPTS -->
	<script src="js/jquery.selectbox-0.2.js"></script>
	<script>
		$(".selectbox").selectbox();
	</script>

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
{% endif %}

templates/searched_tours.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

	Epic Rajasthan Tours | All Tours | Searched tours

{% endblock %}

{% block content %}

	{{block.super}}

	<!-- SubHeader =============================================== -->
	<section class="parallax_window_in" data-parallax="scroll" data-image-src="{% static 'img/searched_tour_banner.jpg' %}" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro">
				<h1>Available Tours</h1>
				<p>search results for "{{ q }}"</p>
			</div>
		</div>
	</section>
	<!-- End section -->
	<!-- End SubHeader ============================================ -->


	<section class="wrapper">
		<div class="divider_border_gray"></div>
		<div class="container">

			{% if tours %}
				{% for tour in tours %}
				<div class="row strip_list wow fadeIn animated" data-wow-delay="0.2s">
					<div class="col-md-5">
						<div class="img_wrapper">
							<div class="ribbon">
								<span>Popular</span>
							</div>
							<div class="price_grid">
								<sup><i class="icon-rupee"></i></sup>{{ tour.price }}
							</div>
							<div class="img_container">
								<a href="{% url 'packages:tour' tour.category.slug tour.slug %}">
									<img src="{{ tour.image.url }}" width="800" height="533" class="img-responsive" alt="">
									<div class="short_info">
										<em>{{ tour.title }}</em>
									</div>
								</a>
							</div>
						</div>
						<!-- End img_wrapper -->
					</div>
					<div class="col-md-7">
						<h3>{{ tour.title }}</h3>
						<p>{{ tour.tourdetail.description }}</p>
						<p><a href="{% url 'packages:tour' tour.category.slug tour.slug %}" class="btn_1">Read more</a>
						</p>
					</div>
				</div>
				<!-- End strip list -->
				{% endfor %}
				<!-- End row -->
			{% else %}
				<div class="alert alert-danger">No Tours Available Yet!</div>
			{% endif %}
		</div>
		<!-- End container -->
		</section>
	<!-- End section -->


	<div class="container margin_60"></div>


{% endblock %}


{% block footer %}

	{{ block.super }}

{% endblock %}


{% block specificscripts %}

	<!-- SPECIFIC SCRIPTS -->
	<script src="js/jquery.selectbox-0.2.js"></script>
	<script>
		$(".selectbox").selectbox();
	</script>

{% endblock %}

templates/tour_detail_exclusions.html
<div class="row">
    <div class="col-md-7">
        <h4>Exclusions</h4>
    </div>
    <div class="col-md-5">
        {% for exclusion in exclusions %}
        <div class="feature-box">
            <div class="feature-box-icon" style="color: #9c2917;">
                <i class="icon-cancel-5"></i>
            </div>
            <div class="feature-box-info">
                <h4>{{exclusion}}</h4>
            </div>
        </div>
        {% endfor %}								
    </div>
</div>

templates/tour_detail_inclusions.html
<div class="row">
    <div class="col-md-7">
        <h4>Inclusions</h4>
    </div>
    <div class="col-md-5">
        {% for inclusion in inclusions %}
        <div class="feature-box">
            <div class="feature-box-icon">
                <i class="icon-ok-4"></i>
            </div>
            <div class="feature-box-info">
                <h4>{{inclusion}}</h4>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/tour_detail_information.html
<h3>Information</h3>
<br>
<p style="font-size: 16px;">{{ tour_detail.description }}</p>

templates/tour_detail_itinerary.html
<h4>Tour Itinerary</h4>
<br>
<div class="panel-group" id="accordion">
    {% for i in tour_itenary %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a style="padding: 15px 5px;" data-toggle="collapse" data-parent="#accordion" href="#collapse{{forloop.counter}}"><b>Day {{forloop.counter}}:</b> {{i.title|title}}
          <i class="icon-angle-circled-down" style="float: right;"></i>
        </a>
      </h4>
    </div>
      <div id="collapse{{forloop.counter}}" class="panel-collapse collapse">
          <div class="panel-body">{{i.description}}</div>
      </div>
  </div>
  {% endfor %}
</div>